version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    env_file:
      - ./.prod.env
    restart: always
    environment:
      # - MONGO_INITDB_DATABASE=${DATABASE_NAME}
      # - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      # - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASS}
      - MONGO_INITDB_DATABASE=nestwnext_schoolsystem
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      # - ${DATABASE_PORT_LOCAL}:${DATABASE_PORT}
      - '27018:27017'
    volumes:
      - /usr/src/app:/data/db
    networks:
      - default

  schoolsystem_backend:
    image: mhramos/schoolsystem_backend:latest
    container_name: schoolsystem_backend
    env_file:
      - ./.prod.env
    command: npm run start:prod
    ports:
      # - ${PORT}:${PORT}
      - '4000:4000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
      - schoolsystem_network

networks:
  schoolsystem_network:
    external: true